# Generated by Django 3.1.4 on 2021-01-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('game_number', models.PositiveSmallIntegerField(verbose_name='Номер игрока')),
                ('role', models.CharField(choices=[('Нападающий', 'Нападающий'), ('Защитник', 'Защитник'), ('Тренер', 'Тренер')], max_length=20)),
                ('team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rthl_site.team', verbose_name='Название команды')),
            ],
        ),
    ]
