# Generated by Django 3.1.4 on 2021-01-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0004_team_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
    ]
