# Generated by Django 3.1.4 on 2021-01-31 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0005_remove_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='biography',
            field=models.TextField(blank=True, default='Нет', verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='player',
            name='disqualified_games_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во дисквал игр.'),
        ),
        migrations.AddField(
            model_name='player',
            name='games_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во игр'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во голов'),
        ),
        migrations.AddField(
            model_name='player',
            name='grip',
            field=models.CharField(choices=[('Л', 'Левый'), ('П', 'Правый')], default='чо', max_length=6, verbose_name='Хват'),
        ),
        migrations.AddField(
            model_name='player',
            name='growth',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='player',
            name='passes_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во передач'),
        ),
        migrations.AddField(
            model_name='player',
            name='penalties_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во штрафов'),
        ),
        migrations.AddField(
            model_name='player',
            name='qualification',
            field=models.CharField(default='Нет', max_length=20, verbose_name='Квалификация'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вес'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_name',
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.ManyToManyField(related_name='player_team', to='rthl_site.Team', verbose_name='Название команды'),
        ),
    ]
