# Generated by Django 3.1.4 on 2021-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0008_auto_20210131_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='img/team.jpg', upload_to='img/teams', verbose_name='Логотип'),
        ),
    ]
