# Generated by Django 3.1.4 on 2021-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0012_auto_20210201_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.SlugField(default='awd', unique=True),
        ),
    ]
