# Generated by Django 3.1.4 on 2021-02-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0012_auto_20210201_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
    ]
