# Generated by Django 3.1.4 on 2021-02-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0013_team_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
