# Generated by Django 3.1.4 on 2021-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0014_auto_20210201_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='url',
            field=models.SlugField(default=models.PositiveSmallIntegerField(verbose_name='Кол-во передач'), unique=True),
        ),
    ]
