# Generated by Django 3.1.4 on 2021-02-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0015_auto_20210201_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='url',
        ),
    ]
