# Generated by Django 3.1.4 on 2021-02-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0016_remove_player_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.SlugField(default='aloblyat', max_length=30),
        ),
    ]
