# Generated by Django 3.1.4 on 2021-02-01 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0018_auto_20210202_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 2, 2), verbose_name='Дата и время'),
        ),
    ]
