# Generated by Django 3.1.4 on 2021-02-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0020_auto_20210202_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='place',
            field=models.CharField(blank=True, max_length=50, verbose_name='Место проведения'),
        ),
    ]
