# Generated by Django 3.1.4 on 2021-02-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0023_auto_20210211_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_player', to='rthl_site.player', verbose_name='Игрок, получивший штраф')),
            ],
        ),
        migrations.CreateModel(
            name='ActionGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_player', to='rthl_site.player', verbose_name='Игрок, забивший гол')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='goals_list',
            field=models.ManyToManyField(related_name='match_goals', to='rthl_site.ActionGoal', verbose_name='Голы'),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_list',
            field=models.ManyToManyField(related_name='match_penalties', to='rthl_site.ActionPenalty', verbose_name='Штрафы'),
        ),
    ]
