# Generated by Django 3.1.4 on 2021-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0025_auto_20210211_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiongoal',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='actionpenalty',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Время'),
        ),
    ]
