# Generated by Django 3.1.4 on 2021-02-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0028_auto_20210211_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiongoal',
            name='time',
        ),
        migrations.RemoveField(
            model_name='actionpenalty',
            name='time',
        ),
        migrations.AddField(
            model_name='actiongoal',
            name='time_minute',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Минута матча'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actiongoal',
            name='time_second',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Секунда матча'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionpenalty',
            name='time_minute',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Минута матча'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionpenalty',
            name='time_second',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Секунда матча'),
            preserve_default=False,
        ),
    ]
