# Generated by Django 3.1.4 on 2021-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0030_auto_20210211_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiongoal',
            name='team_side',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='Команда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionpenalty',
            name='team_side',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='Команда'),
            preserve_default=False,
        ),
    ]
