# Generated by Django 3.1.4 on 2021-02-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0031_auto_20210211_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiongoal',
            name='player',
        ),
        migrations.AddField(
            model_name='actiongoal',
            name='players',
            field=models.ManyToManyField(related_name='goal_players', to='rthl_site.Player', verbose_name='Игроки, забившие гол'),
        ),
    ]
