# Generated by Django 3.1.4 on 2021-02-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0033_lineup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineup',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Составы'},
        ),
        migrations.AlterField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_team', to='rthl_site.team', verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='team_side',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='player',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
    ]
