# Generated by Django 3.1.4 on 2021-02-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0035_auto_20210212_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineup',
            old_name='player',
            new_name='players',
        ),
    ]
