# Generated by Django 3.1.4 on 2021-02-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0037_auto_20210212_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='teamA_total_goals',
        ),
        migrations.RemoveField(
            model_name='match',
            name='teamB_total_goals',
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_tournament', to='rthl_site.tournament', verbose_name='В рамках турнира'),
        ),
    ]
