# Generated by Django 3.1.4 on 2021-02-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0056_tournament_loop_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='Матчи сгенерированы'),
        ),
    ]
