# Generated by Django 3.1.4 on 2021-02-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0057_tournament_is_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loop',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер круга (Плей-офф: 1)'),
        ),
    ]
