# Generated by Django 3.1.4 on 2021-02-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0058_match_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loop',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер круга (Для матча плей-офф оставлять 0)'),
        ),
    ]
