# Generated by Django 3.1.4 on 2021-01-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0006_auto_20210131_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='player',
            name='disqualified_games_count',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во дисквал игр.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='games_count',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во игр'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals_count',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во голов'),
        ),
        migrations.AlterField(
            model_name='player',
            name='grip',
            field=models.CharField(choices=[('Л', 'Левый'), ('П', 'Правый')], max_length=6, verbose_name='Хват'),
        ),
        migrations.AlterField(
            model_name='player',
            name='growth',
            field=models.PositiveSmallIntegerField(verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='player',
            name='passes_count',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во передач'),
        ),
        migrations.AlterField(
            model_name='player',
            name='penalties_count',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во штрафов'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='Вес'),
        ),
    ]
