# Generated by Django 3.1.4 on 2021-02-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0009_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(default='Москва', max_length=30, verbose_name='Город'),
        ),
    ]
