# Generated by Django 3.1.4 on 2021-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0010_team_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('Золотой', 'Золотой'), ('Бронзовый', 'Б'), ('С', 'Серебряный')], default='Нет', max_length=50, verbose_name='Дивизион'),
        ),
    ]
