# Generated by Django 3.1.4 on 2021-02-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0011_team_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Нападающий', 'Нападающий'), ('Защитник', 'Защитник'), ('Тренер', 'Тренер'), ('Гл. Тренер', 'Гл. Тренер')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('Золотой', 'Золотой'), ('Бронзовый', 'Бронзовый'), ('Серебряный', 'Серебряный')], default='Нет', max_length=50, verbose_name='Дивизион'),
        ),
    ]
