# Generated by Django 3.1.4 on 2021-02-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0014_auto_20210201_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='adm_role',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Ассистент', 'Ассистент'), ('Главный Тренер', 'Главный тренер')], default='Нет', max_length=20, verbose_name='Административная роль'),
        ),
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.SlugField(help_text='Адрес на сайте. Пример: rthl.ru/avangard ("rthl.ru/" не вводить)', max_length=30, unique=True),
        ),
    ]
