# Generated by Django 3.1.4 on 2021-02-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0015_auto_20210201_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(unique=True)),
                ('end_year', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='adm_role',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Ассистент', 'Ассистент'), ('Капитан', 'Капитан'), ('Главный Тренер', 'Главный тренер')], default='Нет', max_length=20, verbose_name='Административная роль'),
        ),
        migrations.AlterField(
            model_name='player',
            name='growth',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Вратарь', 'Вратарь'), ('Нападающий', 'Нападающий'), ('Защитник', 'Защитник'), ('Тренер', 'Тренер')], default='Нет', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Вес'),
        ),
    ]
