# Generated by Django 3.1.4 on 2021-02-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0017_auto_20210202_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_year',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Год конца'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_year',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Год начала'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('teamA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='rthl_site.team', verbose_name='Команда 1')),
                ('teamB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='rthl_site.team', verbose_name='Команда 2')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
