# Generated by Django 3.1.4 on 2021-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0022_match_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.AddField(
            model_name='match',
            name='teamA_total_goals',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Общее кол-во голов первой команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamB_total_goals',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Общее кол-во голов первой команды'),
        ),
    ]
