# Generated by Django 3.1.4 on 2021-02-11 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0032_auto_20210211_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Команда')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_match', to='rthl_site.match', verbose_name='Матч')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_player', to='rthl_site.player', verbose_name='Игрок')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_team', to='rthl_site.team', verbose_name='Команда')),
            ],
        ),
    ]
