# Generated by Django 3.1.4 on 2021-02-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0034_auto_20210212_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='player',
        ),
        migrations.AddField(
            model_name='lineup',
            name='player',
            field=models.ManyToManyField(related_name='lineup_player', to='rthl_site.Player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='player',
            name='disqualified_games_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во дисквал игр'),
        ),
        migrations.AlterField(
            model_name='player',
            name='games_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во игр'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во голов'),
        ),
        migrations.AlterField(
            model_name='player',
            name='passes_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во передач'),
        ),
        migrations.AlterField(
            model_name='player',
            name='penalties_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во штрафов'),
        ),
    ]
