# Generated by Django 3.1.4 on 2021-02-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0039_auto_20210214_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionpenalty',
            old_name='players',
            new_name='player',
        ),
    ]
