# Generated by Django 3.1.4 on 2021-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0040_auto_20210214_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='qualification',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Практик', 'Практик'), ('Практик 2.0', 'Практик 2.0'), ('Красный теоретик', 'Красный теоретик'), ('Красный практик', 'Красный практик'), ('Теоретик', 'Теоретик'), ('Любитель', 'Любитель'), ('Юниор', 'Юниор'), ('Спортсмен', 'Спортсмен'), ('Мастер спорта', 'Мастер спорта')], default='Нет', max_length=20, verbose_name='Квалификация'),
        ),
    ]
