# Generated by Django 3.1.4 on 2021-02-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0046_auto_20210224_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.CharField(blank=True, max_length=50, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_teamA', to='rthl_site.team', verbose_name='team А'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_teamB', to='rthl_site.team', verbose_name='team B'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_tournament', to='rthl_site.tournament', verbose_name='In tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='lineup',
            unique_together={('match', 'team_side', 'team')},
        ),
    ]
