# Generated by Django 3.1.4 on 2021-02-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0049_auto_20210225_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(default='Нет', max_length=50, null=True, verbose_name='Дивизион'),
        ),
    ]
