# Generated by Django 3.1.4 on 2021-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0051_auto_20210225_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=50, null=True, verbose_name='Дивизион'),
        ),
    ]
