# Generated by Django 3.1.4 on 2021-02-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0052_auto_20210225_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
    ]
