# Generated by Django 3.1.4 on 2021-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0053_remove_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='tournament_teams', to='rthl_site.Team', verbose_name='Команды чемпионата'),
        ),
    ]
