# Generated by Django 3.1.4 on 2021-02-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthl_site', '0055_remove_tournament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='loop_count',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Количество кругов'),
            preserve_default=False,
        ),
    ]
